version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - identityserver
    ports:
      - "44395:443"

  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"

  #commandapi:
  #  build:
  #    context: .
  #    dockerfile: CommandAPI/Dockerfile
  #  environment:
  #    - ASPNETCORE_URLS=http://*:5006
  #  ports:
  #    - "5006:5006"
  #  networks:
  #    - cqrsnet
