version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - identityserver
    ports:
      - "5200:5100"

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"

  #commandapi:
  #  image: ${DOCKER_REGISTRY-}commandapi
  #  build:
  #    context: .
  #    dockerfile: CommandAPI/Dockerfile


