version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management-alpine

  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    depends_on:
      - sqldata
    labels:
      - "traefik.http.routers.identity.rule=Host(`identity.docker.localhost`)"

  commandapi:
    image: ${DOCKER_REGISTRY-}commandapi
    build:
      context: .
      dockerfile: CommandAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5010
    ports:
      - "5010:5010"
    labels:
      - "traefik.http.routers.command.rule=Host(`command.docker.localhost`)"
    depends_on:
      - rabbitmq
      - identityserver

  queryapi:
    image: ${DOCKER_REGISTRY-}queryapi
    build:
      context: .
      dockerfile: QueryAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5020
    ports:
      - "5020:5020"
    labels:
      - "traefik.http.routers.query.rule=Host(`query.docker.localhost`)"
    depends_on:
      - commandapi
      - rabbitmq
      - identityserver

